[package]
name = "moneylib"
version = "0.2.2"
edition = "2024"
authors = ["Muhammad Fathir Irhas <fathir.irhas@gmail.com>"]
description = "Library to deal with money in Rust."
license = "MIT"
repository = "https://github.com/mfirhas/moneylib"

[dependencies]
rust_decimal = {version = "1.40.0", features = ["maths"]}
rust_decimal_macros = "1.40.0"
iso_currency_lib = "0.1.1"

