[package]
name = "moneylib"
version = "0.0.0"
edition = "2024"
authors = ["Muhammad Fathir Irhas <fathir.irhas@gmail.com>"]
description = "Library to deal with money in Rust."
license = "MIT"
repository = "https://github.com/mfirhas/moneylib"

[dependencies]
rust_decimal = {version = "1.40.0", features = ["maths"]}
rust_decimal_macros = "1.40.0"
accounting = { version = "0.2.0", features = ["decimal"] }
iso_currency = { version = "0.5.3", features = ["iterator"]}
thiserror = "1"
anyhow = "1"
regex = "1"

